2025-03-25 06:25:56.321 +03:00 Error A severe exception occured! Application.NsRequest.StoreRequestCommand StoreRequestCommand { requestTypeId: "3591d3c6-78df-4cd3-8f0f-c3034cdb8b30", subRequestTypes: ["e2dde129-fbd1-44b3-a05d-b6001f0cce9c", "bb70c5a2-f5f3-4046-83e0-f4ab343585f0", "3eca5df6-6259-4f4d-8f42-9c6a78902b63", "982519d3-73cf-4916-a071-b1c18d854af7"], requestInput: "9647501005050" } System.Exception: No connection could be made because the target machine actively refused it. (localhost:44314)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:44314)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Refit.RequestBuilderImplementation.<>c__DisplayClass15_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in c:\temp\releaser\refit\Refit\RequestBuilderImplementation.cs:line 331
--- End of stack trace from previous location ---
   at Refit.Implementation.Generated.InfrastructureServicesIValidationApi.global::Infrastructure.Services.IValidationApi.ValidateMultiple(ValidationRequest request) in D:\apps\NationalSecurity\Infrastructure\InterfaceStubGeneratorV1\Refit.Generator.InterfaceStubGenerator\IValidationApi.g.cs:line 50
   at Infrastructure.Services.ValidationApiService.ValidateMultiple2(String inputs, String inputType) in D:\apps\NationalSecurity\Infrastructure\Services\ValidationApiService.cs:line 27
   --- End of inner exception stack trace ---
   at Infrastructure.Services.ValidationApiService.ValidateMultiple2(String inputs, String inputType) in D:\apps\NationalSecurity\Infrastructure\Services\ValidationApiService.cs:line 42
   at Application.NsRequest.StoreRequestCommand.StoreRequestCommandHandler.Handle(StoreRequestCommand request, CancellationToken cancellationToken) in D:\apps\NationalSecurity\Application\NsRequest\StoreRequestCommand.cs:line 39
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
 
2025-03-25 06:27:39.564 +03:00 Fatal Something went wrong while handling request of type! Application.NsRequest.StoreRequestCommand StoreRequestCommand { requestTypeId: "3591d3c6-78df-4cd3-8f0f-c3034cdb8b30", subRequestTypes: ["e2dde129-fbd1-44b3-a05d-b6001f0cce9c", "bb70c5a2-f5f3-4046-83e0-f4ab343585f0", "3eca5df6-6259-4f4d-8f42-9c6a78902b63", "982519d3-73cf-4916-a071-b1c18d854af7"], requestInput: "9647501005050
9647501005051" } DbExecuteException { Sql: "insert into REQUESTFLOWS(ID,REQUESTID,STATUS,ASSIGNEDTOSECURITY,ASSIGNEDTOARCHIVE,SECURITYMESSAGE,ARCHIVEMESSAGE,SECURITYSTATUS,ARCHIVESTATUS,CREATEDAT) 
                                                                      values(:Id,:requestId,:status,:assignedToSecurity,:assignedToArchive,:securityMessage,:archiveMessage,:securityStatus,:archiveStatus,CreatedAt)", Param: NsRequestFlows { requestId: "120eb55f-874b-4990-b775-0307c662ef2a", status: "CREATED", assignedToSecurity: "", assignedToArchive: "", securityMessage: "", archiveMessage: "", securityStatus: "REQUIRED", archiveStatus: "REQUIRED", Id: "8c2dd9f2-aae4-4744-875f-cb8d3cb29460", CreatedAt: 03/25/2025 06:27:38, UpdatedAt: 03/25/2025 06:27:38 }, InnerException: OracleException { OracleLogicalTransaction: OracleLogicalTransaction { Committed: null, UserCallCompleted: null, ConnectionString: null, LogicalTransactionId: null }, Errors: [OracleError { DataSource: "", Message: "ORA-00984: column not allowed here
", Number: 984, ParseErrorOffset: 358, Procedure: "", Source: "Oracle Data Provider for .NET, Managed Driver", ArrayBindIndex: -1 }], DataSource: "", Message: "ORA-00984: column not allowed here", Procedure: "", Source: "Oracle Data Provider for .NET, Managed Driver", Number: 984, IsRecoverable: False, IsTransient: False, SqlState: null, BatchCommand: null, ErrorCode: -2147467259, TargetSite: Int32 VerifyExecution(Int32 ByRef, Boolean, OracleInternal.Common.SqlStatementType, Int32, Oracle.ManagedDataAccess.Client.OracleException ByRef, Boolean ByRef, Boolean), Data: [], InnerException: null, HelpLink: null, HResult: -2147467259, StackTrace: "   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 662
   at Infrastructure.Services.DbService.ExecuteWithTransaction(IList`1 commands) in D:\apps\NationalSecurity\Infrastructure\Services\DbService.cs:line 62" }, TargetSite: Void MoveNext(), Message: "ORA-00984: column not allowed here", Data: [], HelpLink: null, Source: "Infrastructure", HResult: -2146233088, StackTrace: "   at Infrastructure.Services.DbService.ExecuteWithTransaction(IList`1 commands) in D:\apps\NationalSecurity\Infrastructure\Services\DbService.cs:line 68
   at Infrastructure.Services.RequestService.Save(Requests request) in D:\apps\NationalSecurity\Infrastructure\Services\RequestService.cs:line 41
   at Application.NsRequest.StoreRequestCommand.StoreRequestCommandHandler.Handle(StoreRequestCommand request, CancellationToken cancellationToken) in D:\apps\NationalSecurity\Application\NsRequest\StoreRequestCommand.cs:line 82
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)" } null  
